### ISSUE TITLE
Error occurs when executing "nrnivmodl -coreneuron mod", while "nrnivmodl mod" succeeded

### ISSUE THREAD

**Issue by yult0821** [suny-downstate-medical-center/S1_netpyne#1]
Hey guys, I run into a problem when executing `nrnivmodl -coreneuron mod`, while `nrnivmodl mod` succeeded. I am a novice to NEURON simulator. Any advices will be appreciated.  Thanks a lot!

Follwing shows the output when executing `nrnivmodl -coreneuron mod`, and error occurs when translating `ProbAMPANMDA_EMS.cpp` and `ProbGABAAB_EMS.cpp`. Please refer to the last part of the record.

```
(base) root@b5953ae00c692011ec0b98d0e9f1ef15e5e8-yult18-0:/userhome/BrainSim/netpyne/S1_netpyne/sim# nrnivmodl -coreneuron mod/
/userhome/BrainSim/netpyne/S1_netpyne/sim
Mod files: "mod/Ca.mod" "mod/CaDynamics_E2.mod" "mod/Ca_HVA.mod" "mod/Ca_LVAst.mod" "mod/DetAMPANMDA.mod" "mod/DetGABAAB.mod" "mod/HCN1.mod" "mod/HH2.mod" "mod/IC.mod" "mod/IKsin.mod" "mod/IT.mod" "mod/IT2.mod" "mod/Ih.mod" "mod/Im.mod" "mod/K_Pst.mod" "mod/K_Tst.mod" "mod/KdShu2007.mod" "mod/MyExp2SynBB.mod" "mod/MyExp2SynNMDABB.mod" "mod/NaTa_t.mod" "mod/NaTs2_t.mod" "mod/Nap_Et2.mod" "mod/Nca.mod" "mod/ProbAMPANMDA_EMS.mod" "mod/ProbGABAAB_EMS.mod" "mod/SK_E2.mod" "mod/SKv3_1.mod" "mod/StochKv.mod" "mod/StochKv_det.mod" "mod/StochKv_deterministic.mod" "mod/ar_traub.mod" "mod/cadad.mod" "mod/cadyn.mod" "mod/cagk.mod" "mod/cal_mh.mod" "mod/cal_mig.mod" "mod/can_mig.mod" "mod/cancr.mod" "mod/canin.mod" "mod/cat_mig.mod" "mod/cat_traub.mod" "mod/catcb.mod" "mod/ch_CavL.mod" "mod/ch_CavN.mod" "mod/ch_KCaS.mod" "mod/ch_Kdrfastngf.mod" "mod/ch_KvAngf.mod" "mod/ch_KvCaB.mod" "mod/ch_Navngf.mod" "mod/ch_leak.mod" "mod/gabab.mod" "mod/h_BS.mod" "mod/h_harnett.mod" "mod/h_kole.mod" "mod/h_migliore.mod" "mod/hin.mod" "mod/htc.mod" "mod/ican_sidi.mod" "mod/iccr.mod" "mod/iconc_Ca.mod" "mod/ikscr.mod" "mod/kBK.mod" "mod/kap_BS.mod" "mod/kapcb.mod" "mod/kapin.mod" "mod/kca.mod" "mod/kctin.mod" "mod/kdmc_BS.mod" "mod/kdr_BS.mod" "mod/kdrcr.mod" "mod/kdrin.mod" "mod/kl.mod" "mod/km.mod" "mod/kv.mod" "mod/my_exp2syn.mod" "mod/nafcr.mod" "mod/nafx.mod" "mod/nap_sidi.mod" "mod/nax_BS.mod" "mod/naz.mod" "mod/savedist.mod" "mod/tia.mod" "mod/vecstim.mod"

Creating x86_64 directory for .o files.

COBJS=''
[INFO] Running: make -j4 -f /root/miniconda3/lib/python3.8/site-packages/neuron/.data/share/coreneuron/nrnivmodl_core_makefile ROOT=/root/miniconda3/lib/python3.8/site-packages/neuron/.data MODS_PATH=x86_64/corenrn/mod2c BUILD_TYPE=SHARED NRN_PRCELLSTATE=0
Default NMODL flags: 
Translating x86_64/corenrn/mod2c/Ca.mod into x86_64/corenrn/mod2c//Ca.cpp
cvode_emit=0 cvode_not_allowed=0
Translating x86_64/corenrn/mod2c/CaDynamics_E2.mod into x86_64/corenrn/mod2c//CaDynamics_E2.cpp
cvode_emit=0 cvode_not_allowed=0
diff: x86_64/corenrn/mod2c/_mod_func.cpp: No such file or directory
Thread Safe
Translating x86_64/corenrn/mod2c/Ca_HVA.mod into x86_64/corenrn/mod2c//Ca_HVA.cpp
cvode_emit=0 cvode_not_allowed=0
Thread Safe
Thread Safe
Translating x86_64/corenrn/mod2c/Ca_LVAst.mod into x86_64/corenrn/mod2c//Ca_LVAst.cpp
cvode_emit=0 cvode_not_allowed=0
Thread Safe
Translating x86_64/corenrn/mod2c/DetAMPANMDA.mod into x86_64/corenrn/mod2c//DetAMPANMDA.cpp
cvode_emit=0 cvode_not_allowed=0
Translating x86_64/corenrn/mod2c/HCN1.mod into x86_64/corenrn/mod2c//HCN1.cpp
cvode_emit=0 cvode_not_allowed=0
Thread Safe
Translating x86_64/corenrn/mod2c/DetGABAAB.mod into x86_64/corenrn/mod2c//DetGABAAB.cpp
cvode_emit=0 cvode_not_allowed=0
Thread Safe
Translating x86_64/corenrn/mod2c/HH2.mod into x86_64/corenrn/mod2c//HH2.cpp
cvode_emit=0 cvode_not_allowed=0
Thread Safe
Thread Safe
Translating x86_64/corenrn/mod2c/IC.mod into x86_64/corenrn/mod2c//IC.cpp
cvode_emit=0 cvode_not_allowed=0
Translating x86_64/corenrn/mod2c/IKsin.mod into x86_64/corenrn/mod2c//IKsin.cpp
cvode_emit=0 cvode_not_allowed=0
Translating x86_64/corenrn/mod2c/IT.mod into x86_64/corenrn/mod2c//IT.cpp
cvode_emit=0 cvode_not_allowed=0
Warning: Default 2 of PARAMETER cao will be ignored and set by NEURON.
Warning: Default 0.00024 of PARAMETER cai will be ignored and set by NEURON.
Thread Safe
Thread Safe
Translating x86_64/corenrn/mod2c/IT2.mod into x86_64/corenrn/mod2c//IT2.cpp
Warning: celsius undefined. (declared within VERBATIM?)
cvode_emit=0 cvode_not_allowed=0
Thread Safe
Thread Safe
Translating x86_64/corenrn/mod2c/Ih.mod into x86_64/corenrn/mod2c//Ih.cpp
cvode_emit=0 cvode_not_allowed=0
Translating x86_64/corenrn/mod2c/Im.mod into x86_64/corenrn/mod2c//Im.cpp
cvode_emit=0 cvode_not_allowed=0
Thread Safe
Translating x86_64/corenrn/mod2c/K_Pst.mod into x86_64/corenrn/mod2c//K_Pst.cpp
cvode_emit=0 cvode_not_allowed=0
Thread Safe
Translating x86_64/corenrn/mod2c/K_Tst.mod into x86_64/corenrn/mod2c//K_Tst.cpp
cvode_emit=0 cvode_not_allowed=0
Thread Safe
Thread Safe
Translating x86_64/corenrn/mod2c/KdShu2007.mod into x86_64/corenrn/mod2c//KdShu2007.cpp
cvode_emit=0 cvode_not_allowed=0
Translating x86_64/corenrn/mod2c/MyExp2SynBB.mod into x86_64/corenrn/mod2c//MyExp2SynBB.cpp
cvode_emit=0 cvode_not_allowed=0
Thread Safe
Thread Safe
Translating x86_64/corenrn/mod2c/MyExp2SynNMDABB.mod into x86_64/corenrn/mod2c//MyExp2SynNMDABB.cpp
INCLUDEing x86_64/corenrn/mod2c/ghk.inc
Warning: celsius undefined. (declared within VERBATIM?)
cvode_emit=0 cvode_not_allowed=0
Translating x86_64/corenrn/mod2c/NaTa_t.mod into x86_64/corenrn/mod2c//NaTa_t.cpp
cvode_emit=0 cvode_not_allowed=0
Thread Safe
Thread Safe
Translating x86_64/corenrn/mod2c/NaTs2_t.mod into x86_64/corenrn/mod2c//NaTs2_t.cpp
cvode_emit=0 cvode_not_allowed=0
Translating x86_64/corenrn/mod2c/Nap_Et2.mod into x86_64/corenrn/mod2c//Nap_Et2.cpp
cvode_emit=0 cvode_not_allowed=0
Thread Safe
Thread Safe
Translating x86_64/corenrn/mod2c/Nca.mod into x86_64/corenrn/mod2c//Nca.cpp
cvode_emit=0 cvode_not_allowed=0
Translating x86_64/corenrn/mod2c/ProbAMPANMDA_EMS.mod into x86_64/corenrn/mod2c//ProbAMPANMDA_EMS.cpp
Notice: This mechanism cannot be used with CVODE
Warning: dt undefined. (declared within VERBATIM?)
Warning: value undefined. (declared within VERBATIM?)
cvode_emit=0 cvode_not_allowed=1
Thread Safe
Translating x86_64/corenrn/mod2c/ProbGABAAB_EMS.mod into x86_64/corenrn/mod2c//ProbGABAAB_EMS.cpp
Notice: This mechanism cannot be used with CVODE
Warning: dt undefined. (declared within VERBATIM?)
Warning: value undefined. (declared within VERBATIM?)
cvode_emit=0 cvode_not_allowed=1
Thread Safe
Thread Safe
Translating x86_64/corenrn/mod2c/SK_E2.mod into x86_64/corenrn/mod2c//SK_E2.cpp
cvode_emit=0 cvode_not_allowed=0
Thread Safe
Translating x86_64/corenrn/mod2c/SKv3_1.mod into x86_64/corenrn/mod2c//SKv3_1.cpp
cvode_emit=0 cvode_not_allowed=0
Thread Safe
Translating x86_64/corenrn/mod2c/StochKv.mod into x86_64/corenrn/mod2c//StochKv.cpp
Notice: This mechanism cannot be used with CVODE
Warning: bnl undefined. (declared within VERBATIM?)
Warning: value undefined. (declared within VERBATIM?)
cvode_emit=0 cvode_not_allowed=1
Translating x86_64/corenrn/mod2c/StochKv_det.mod into x86_64/corenrn/mod2c//StochKv_det.cpp
Warning: bnl undefined. (declared within VERBATIM?)
Warning: value undefined. (declared within VERBATIM?)
cvode_emit=0 cvode_not_allowed=0
Thread Safe
Translating x86_64/corenrn/mod2c/StochKv_deterministic.mod into x86_64/corenrn/mod2c//StochKv_deterministic.cpp
cvode_emit=0 cvode_not_allowed=0
Thread Safe
Thread Safe
Translating x86_64/corenrn/mod2c/ar_traub.mod into x86_64/corenrn/mod2c//ar_traub.cpp
cvode_emit=0 cvode_not_allowed=0
Thread Safe
Translating x86_64/corenrn/mod2c/cadad.mod into x86_64/corenrn/mod2c//cadad.cpp
cvode_emit=0 cvode_not_allowed=0
Translating x86_64/corenrn/mod2c/cadyn.mod into x86_64/corenrn/mod2c//cadyn.cpp
Thread Safe
cvode_emit=0 cvode_not_allowed=0
Translating x86_64/corenrn/mod2c/cagk.mod into x86_64/corenrn/mod2c//cagk.cpp
cvode_emit=0 cvode_not_allowed=0
Thread Safe
Thread Safe
Translating x86_64/corenrn/mod2c/cal_mh.mod into x86_64/corenrn/mod2c//cal_mh.cpp
cvode_emit=0 cvode_not_allowed=0
Thread Safe
Translating x86_64/corenrn/mod2c/cal_mig.mod into x86_64/corenrn/mod2c//cal_mig.cpp
cvode_emit=0 cvode_not_allowed=0
Warning: Default 2 of PARAMETER cao will be ignored and set by NEURON.
Warning: Default 5e-05 of PARAMETER cai will be ignored and set by NEURON.
Thread Safe
Translating x86_64/corenrn/mod2c/can_mig.mod into x86_64/corenrn/mod2c//can_mig.cpp
cvode_emit=0 cvode_not_allowed=0
Warning: Default 2 of PARAMETER cao will be ignored and set by NEURON.
Warning: Default 5e-05 of PARAMETER cai will be ignored and set by NEURON.
Thread Safe
Translating x86_64/corenrn/mod2c/cancr.mod into x86_64/corenrn/mod2c//cancr.cpp
cvode_emit=0 cvode_not_allowed=0
Thread Safe
Translating x86_64/corenrn/mod2c/canin.mod into x86_64/corenrn/mod2c//canin.cpp
cvode_emit=0 cvode_not_allowed=0
Translating x86_64/corenrn/mod2c/cat_mig.mod into x86_64/corenrn/mod2c//cat_mig.cpp
cvode_emit=0 cvode_not_allowed=0
Warning: Default 2 of PARAMETER cao will be ignored and set by NEURON.
Warning: Default 5e-05 of PARAMETER cai will be ignored and set by NEURON.
Warning: Default 25 of PARAMETER celsius will be ignored and set by NEURON.
Thread Safe
Translating x86_64/corenrn/mod2c/cat_traub.mod into x86_64/corenrn/mod2c//cat_traub.cpp
cvode_emit=0 cvode_not_allowed=0
Thread Safe
Translating x86_64/corenrn/mod2c/catcb.mod into x86_64/corenrn/mod2c//catcb.cpp
cvode_emit=0 cvode_not_allowed=0
Thread Safe
Thread Safe
Translating x86_64/corenrn/mod2c/ch_CavL.mod into x86_64/corenrn/mod2c//ch_CavL.cpp
cvode_emit=0 cvode_not_allowed=0
Translating x86_64/corenrn/mod2c/ch_CavN.mod into x86_64/corenrn/mod2c//ch_CavN.cpp
Notice: This mechanism cannot be used with CVODE
cvode_emit=0 cvode_not_allowed=1
Thread Safe
Translating x86_64/corenrn/mod2c/ch_KCaS.mod into x86_64/corenrn/mod2c//ch_KCaS.cpp
Notice: This mechanism cannot be used with CVODE
cvode_emit=0 cvode_not_allowed=1
Thread Safe
Thread Safe
Translating x86_64/corenrn/mod2c/ch_Kdrfastngf.mod into x86_64/corenrn/mod2c//ch_Kdrfastngf.cpp
Notice: This mechanism cannot be used with CVODE
cvode_emit=0 cvode_not_allowed=1
Thread Safe
Translating x86_64/corenrn/mod2c/ch_KvAngf.mod into x86_64/corenrn/mod2c//ch_KvAngf.cpp
cvode_emit=0 cvode_not_allowed=0
Translating x86_64/corenrn/mod2c/ch_KvCaB.mod into x86_64/corenrn/mod2c//ch_KvCaB.cpp
cvode_emit=0 cvode_not_allowed=0
Thread Safe
Translating x86_64/corenrn/mod2c/ch_Navngf.mod into x86_64/corenrn/mod2c//ch_Navngf.cpp
Notice: This mechanism cannot be used with CVODE
cvode_emit=0 cvode_not_allowed=1
Thread Safe
Thread Safe
Translating x86_64/corenrn/mod2c/ch_leak.mod into x86_64/corenrn/mod2c//ch_leak.cpp
cvode_emit=0 cvode_not_allowed=0
Thread Safe
Translating x86_64/corenrn/mod2c/exp2syn.mod into x86_64/corenrn/mod2c//exp2syn.cpp
cvode_emit=0 cvode_not_allowed=0
Thread Safe
Translating x86_64/corenrn/mod2c/expsyn.mod into x86_64/corenrn/mod2c//expsyn.cpp
cvode_emit=0 cvode_not_allowed=0
Translating x86_64/corenrn/mod2c/gabab.mod into x86_64/corenrn/mod2c//gabab.cpp
cvode_emit=0 cvode_not_allowed=0
Translating x86_64/corenrn/mod2c/h_BS.mod into x86_64/corenrn/mod2c//h_BS.cpp
cvode_emit=0 cvode_not_allowed=0
Warning: Default 34 of PARAMETER celsius will be ignored and set by NEURON.
Thread Safe
Thread Safe
Translating x86_64/corenrn/mod2c/h_harnett.mod into x86_64/corenrn/mod2c//h_harnett.cpp
cvode_emit=0 cvode_not_allowed=0
Thread Safe
Thread Safe
Translating x86_64/corenrn/mod2c/h_kole.mod into x86_64/corenrn/mod2c//h_kole.cpp
cvode_emit=0 cvode_not_allowed=0
Translating x86_64/corenrn/mod2c/h_migliore.mod into x86_64/corenrn/mod2c//h_migliore.cpp
cvode_emit=0 cvode_not_allowed=0
Thread Safe
Thread Safe
Translating x86_64/corenrn/mod2c/hh.mod into x86_64/corenrn/mod2c//hh.cpp
cvode_emit=0 cvode_not_allowed=0
Translating x86_64/corenrn/mod2c/hin.mod into x86_64/corenrn/mod2c//hin.cpp
cvode_emit=0 cvode_not_allowed=0
Warning: Default -10 of PARAMETER ehi will be ignored and set by NEURON.
Thread Safe
Thread Safe
Translating x86_64/corenrn/mod2c/htc.mod into x86_64/corenrn/mod2c//htc.cpp
NEURON's CVode method ignores conservation
Warning: celsius undefined. (declared within VERBATIM?)
cvode_emit=0 cvode_not_allowed=0
Translating x86_64/corenrn/mod2c/ican_sidi.mod into x86_64/corenrn/mod2c//ican_sidi.cpp
cvode_emit=0 cvode_not_allowed=0
Warning: Default 36 of PARAMETER celsius will be ignored and set by NEURON.
Translating x86_64/corenrn/mod2c/iccr.mod into x86_64/corenrn/mod2c//iccr.cpp
cvode_emit=0 cvode_not_allowed=0
Thread Safe
Thread Safe
Translating x86_64/corenrn/mod2c/iconc_Ca.mod into x86_64/corenrn/mod2c//iconc_Ca.cpp
cvode_emit=0 cvode_not_allowed=0
Thread Safe
Thread Safe
Translating x86_64/corenrn/mod2c/ikscr.mod into x86_64/corenrn/mod2c//ikscr.cpp
cvode_emit=0 cvode_not_allowed=0
Thread Safe
Translating x86_64/corenrn/mod2c/kBK.mod into x86_64/corenrn/mod2c//kBK.cpp
cvode_emit=0 cvode_not_allowed=0
Translating x86_64/corenrn/mod2c/kap_BS.mod into x86_64/corenrn/mod2c//kap_BS.cpp
cvode_emit=0 cvode_not_allowed=0
Thread Safe
Translating x86_64/corenrn/mod2c/kapcb.mod into x86_64/corenrn/mod2c//kapcb.cpp
cvode_emit=0 cvode_not_allowed=0
Thread Safe
Thread Safe
Translating x86_64/corenrn/mod2c/kapin.mod into x86_64/corenrn/mod2c//kapin.cpp
cvode_emit=0 cvode_not_allowed=0
Translating x86_64/corenrn/mod2c/kca.mod into x86_64/corenrn/mod2c//kca.cpp
cvode_emit=0 cvode_not_allowed=0
Thread Safe
Thread Safe
Translating x86_64/corenrn/mod2c/kctin.mod into x86_64/corenrn/mod2c//kctin.cpp
NEURON's CVode method ignores conservation
cvode_emit=0 cvode_not_allowed=0
Translating x86_64/corenrn/mod2c/kdmc_BS.mod into x86_64/corenrn/mod2c//kdmc_BS.cpp
Thread Safe
cvode_emit=0 cvode_not_allowed=0
Thread Safe
Translating x86_64/corenrn/mod2c/kdr_BS.mod into x86_64/corenrn/mod2c//kdr_BS.cpp
cvode_emit=0 cvode_not_allowed=0
Translating x86_64/corenrn/mod2c/kdrcr.mod into x86_64/corenrn/mod2c//kdrcr.cpp
cvode_emit=0 cvode_not_allowed=0
Thread Safe
Translating x86_64/corenrn/mod2c/kdrin.mod into x86_64/corenrn/mod2c//kdrin.cpp
cvode_emit=0 cvode_not_allowed=0
Thread Safe
Translating x86_64/corenrn/mod2c/kl.mod into x86_64/corenrn/mod2c//kl.cpp
cvode_emit=0 cvode_not_allowed=0
Thread Safe
Thread Safe
Translating x86_64/corenrn/mod2c/km.mod into x86_64/corenrn/mod2c//km.cpp
cvode_emit=0 cvode_not_allowed=0
Translating x86_64/corenrn/mod2c/kv.mod into x86_64/corenrn/mod2c//kv.cpp
cvode_emit=0 cvode_not_allowed=0
Thread Safe
Translating x86_64/corenrn/mod2c/my_exp2syn.mod into x86_64/corenrn/mod2c//my_exp2syn.cpp
cvode_emit=0 cvode_not_allowed=0
Thread Safe
Thread Safe
Translating x86_64/corenrn/mod2c/nafcr.mod into x86_64/corenrn/mod2c//nafcr.cpp
cvode_emit=0 cvode_not_allowed=0
Warning: Default 55 of PARAMETER ena will be ignored and set by NEURON.
Thread Safe
Translating x86_64/corenrn/mod2c/nafx.mod into x86_64/corenrn/mod2c//nafx.cpp
cvode_emit=0 cvode_not_allowed=0
Warning: Default 55 of PARAMETER ena will be ignored and set by NEURON.
Translating x86_64/corenrn/mod2c/nap_sidi.mod into x86_64/corenrn/mod2c//nap_sidi.cpp
cvode_emit=0 cvode_not_allowed=0
Thread Safe
Translating x86_64/corenrn/mod2c/nax_BS.mod into x86_64/corenrn/mod2c//nax_BS.cpp
cvode_emit=0 cvode_not_allowed=0
Thread Safe
Translating x86_64/corenrn/mod2c/naz.mod into x86_64/corenrn/mod2c//naz.cpp
cvode_emit=0 cvode_not_allowed=0
Thread Safe
Thread Safe
Translating x86_64/corenrn/mod2c/netstim.mod into x86_64/corenrn/mod2c//netstim.cpp
cvode_emit=0 cvode_not_allowed=0
Notice: ARTIFICIAL_CELL is a synonym for POINT_PROCESS which hints that it
only affects and is affected by discrete events. As such it is not
located in a section and is not associated with an integrator
Translating x86_64/corenrn/mod2c/passive.mod into x86_64/corenrn/mod2c//passive.cpp
cvode_emit=0 cvode_not_allowed=0
Thread Safe
Thread Safe
Translating x86_64/corenrn/mod2c/pattern.mod into x86_64/corenrn/mod2c//pattern.cpp
cvode_emit=0 cvode_not_allowed=0
Notice: ARTIFICIAL_CELL is a synonym for POINT_PROCESS which hints that it
only affects and is affected by discrete events. As such it is not
located in a section and is not associated with an integrator
Translating x86_64/corenrn/mod2c/savedist.mod into x86_64/corenrn/mod2c//savedist.cpp
cvode_emit=0 cvode_not_allowed=0
Thread Safe
Thread Safe
Translating x86_64/corenrn/mod2c/stim.mod into x86_64/corenrn/mod2c//stim.cpp
cvode_emit=0 cvode_not_allowed=0
Translating x86_64/corenrn/mod2c/svclmp.mod into x86_64/corenrn/mod2c//svclmp.cpp
cvode_emit=0 cvode_not_allowed=0
Thread Safe
Translating x86_64/corenrn/mod2c/tia.mod into x86_64/corenrn/mod2c//tia.cpp
Warning: celsius undefined. (declared within VERBATIM?)
cvode_emit=0 cvode_not_allowed=0
Thread Safe
Translating x86_64/corenrn/mod2c/vecstim.mod into x86_64/corenrn/mod2c//vecstim.cpp
cvode_emit=0 cvode_not_allowed=0
Notice: ARTIFICIAL_CELL is a synonym for POINT_PROCESS which hints that it
only affects and is affected by discrete events. As such it is not
located in a section and is not associated with an integrator
Thread Safe
Thread Safe
x86_64/corenrn/mod2c/ProbAMPANMDA_EMS.cpp: In function ‘int coreneuron::setRNG_ProbAMPANMDA_EMS(int, int, double*, coreneuron::Datum*, coreneuron::ThreadDatum*, coreneuron::NrnThread*, double)’:
x86_64/corenrn/mod2c/ProbAMPANMDA_EMS.cpp:627:31: error: ‘_p_rng’ was not declared in this scope
         void** pv = (void**)(&_p_rng);
                               ^~~~~~
x86_64/corenrn/mod2c/ProbGABAAB_EMS.cpp: In function ‘int coreneuron::setRNG_ProbGABAAB_EMS(int, int, double*, coreneuron::Datum*, coreneuron::ThreadDatum*, coreneuron::NrnThread*, double)’:
x86_64/corenrn/mod2c/ProbGABAAB_EMS.cpp:612:31: error: ‘_p_rng’ was not declared in this scope
         void** pv = (void**)(&_p_rng);
                               ^~~~~~
x86_64/corenrn/mod2c/ProbAMPANMDA_EMS.cpp:627:31: note: suggested alternative: ‘__ynl’
         void** pv = (void**)(&_p_rng);
                               ^~~~~~
                               __ynl
x86_64/corenrn/mod2c/ProbGABAAB_EMS.cpp:612:31: note: suggested alternative: ‘__ynl’
         void** pv = (void**)(&_p_rng);
                               ^~~~~~
                               __ynl
x86_64/corenrn/mod2c/ProbAMPANMDA_EMS.cpp:628:13: error: ‘ifarg’ was not declared in this scope
         if( ifarg(1)) {
             ^~~~~
x86_64/corenrn/mod2c/ProbGABAAB_EMS.cpp:613:13: error: ‘ifarg’ was not declared in this scope
         if( ifarg(1)) {
             ^~~~~
x86_64/corenrn/mod2c/ProbAMPANMDA_EMS.cpp: In function ‘double coreneuron::urand_ProbAMPANMDA_EMS(int, int, double*, coreneuron::Datum*, coreneuron::ThreadDatum*, coreneuron::NrnThread*, double)’:
x86_64/corenrn/mod2c/ProbAMPANMDA_EMS.cpp:657:13: error: ‘_p_rng’ was not declared in this scope
         if (_p_rng) {
             ^~~~~~
x86_64/corenrn/mod2c/ProbGABAAB_EMS.cpp: In function ‘double coreneuron::urand_ProbGABAAB_EMS(int, int, double*, coreneuron::Datum*, coreneuron::ThreadDatum*, coreneuron::NrnThread*, double)’:
x86_64/corenrn/mod2c/ProbGABAAB_EMS.cpp:642:13: error: ‘_p_rng’ was not declared in this scope
         if (_p_rng) {
             ^~~~~~
x86_64/corenrn/mod2c/ProbAMPANMDA_EMS.cpp:657:13: note: suggested alternative: ‘__ynl’
         if (_p_rng) {
             ^~~~~~
             __ynl
x86_64/corenrn/mod2c/ProbAMPANMDA_EMS.cpp:667:10: error: ‘scop_random’ was not declared in this scope
  value = scop_random ( 1.0 ) ;
          ^~~~~~~~~~~
x86_64/corenrn/mod2c/ProbGABAAB_EMS.cpp:642:13: note: suggested alternative: ‘__ynl’
         if (_p_rng) {
             ^~~~~~
             __ynl
x86_64/corenrn/mod2c/ProbGABAAB_EMS.cpp:652:10: error: ‘scop_random’ was not declared in this scope
  value = scop_random ( 1.0 ) ;
          ^~~~~~~~~~~
x86_64/corenrn/mod2c/ProbAMPANMDA_EMS.cpp:667:10: note: suggested alternative: ‘srandom’
  value = scop_random ( 1.0 ) ;
          ^~~~~~~~~~~
          srandom
x86_64/corenrn/mod2c/ProbGABAAB_EMS.cpp:652:10: note: suggested alternative: ‘srandom’
  value = scop_random ( 1.0 ) ;
          ^~~~~~~~~~~
          srandom
/root/miniconda3/lib/python3.8/site-packages/neuron/.data/share/coreneuron/nrnivmodl_core_makefile:248: recipe for target 'x86_64/corenrn/build/ProbAMPANMDA_EMS.o' failed
make: *** [x86_64/corenrn/build/ProbAMPANMDA_EMS.o] Error 1
make: *** Waiting for unfinished jobs....
/root/miniconda3/lib/python3.8/site-packages/neuron/.data/share/coreneuron/nrnivmodl_core_makefile:248: recipe for target 'x86_64/corenrn/build/ProbGABAAB_EMS.o' failed
make: *** [x86_64/corenrn/build/ProbGABAAB_EMS.o] Error 1
Traceback (most recent call last):
  File "/root/miniconda3/bin/nrnivmodl", line 94, in <module>
    subprocess.check_call([exe, *sys.argv[1:]])
  File "/root/miniconda3/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/root/miniconda3/lib/python3.8/site-packages/neuron/.data/bin/nrnivmodl', '-coreneuron', 'mod/']' returned non-zero exit status 2.
```

**Comment by yult0821** [comment]
As instructed, one should the coreneuron branch to run with CoreNeuron library. Then, everything goes fine.

**Comment by pramodk** [comment]
@iomaganaris: what would be needed to bring coreneuron branch as a PR to the master?
